import { useState, useMemo, useEffect, useRef } from "react";

/*
 * CCEL Weekly News - Production App
 * Loads data from /data/news.json (generated by backend)
 * Supports multi-category (categories array) with AND filter logic
 */

/* ===== DESIGN TOKENS ===== */
const C = {
  white: "#ffffff", bg: "#f2f2f2", bgAlt: "#fafafa",
  border: "#e5e5e5", borderLight: "#eeeeee",
  gray100: "#f7f7f7", gray300: "#cccccc", gray500: "#999999",
  gray600: "#777777", gray700: "#555555",
  textBody: "#444444", textDark: "#222222",
  accent: "#0066FF", accentSoft: "rgba(0,102,255,0.07)",
  footerBg: "#2c3034", footerText: "#adb5bd", footerDim: "#6c757d",
  ccelGold: "#E8A317",
  shadow: "0 1px 6px rgba(0,0,0,0.06)",
  shadowHover: "0 4px 16px rgba(0,0,0,0.10)",
};

const catColors = {
  dft: "#6C5CE7", catalysis: "#00A878", electrochemistry: "#0066FF",
  battery: "#E17055", ml: "#D63384", policy: "#B8860B",
};
const cc = id => catColors[id] || C.gray500;

const CATEGORIES = [
  { id: "dft", label: "DFT / Comp. Chem." },
  { id: "catalysis", label: "Catalysis" },
  { id: "electrochemistry", label: "Electrochem / FC" },
  { id: "battery", label: "Battery" },
  { id: "ml", label: "ML / MLIP" },
  { id: "policy", label: "Industry / Policy" },
];

const DEFAULT_GROUPS = [
  { id: "ccel", name: "CCEL" },
  { id: "norskov", name: "Norskov" },
  { id: "persson", name: "Persson" },
  { id: "curtarolo", name: "Curtarolo" },
  { id: "noguera", name: "Noguera" },
];

function normalizeSource(s){return /^ar[Xx]iv/i.test(s)?"arXiv":s;}

/* ===== Helper: get categories array from paper (backward compat) ===== */
function getPaperCats(d) {
  if (d.categories && Array.isArray(d.categories) && d.categories.length > 0) {
    return d.categories;
  }
  // Fallback: single category field
  const cat = d.category || d.cat || "";
  return cat ? [cat] : [];
}

function getSortedPaperCatIds(d){
  const cats=getPaperCats(d);
  return [...cats].sort((a,b)=>{
    const la=CATEGORIES.find(c=>c.id===a)?.label||a;
    const lb=CATEGORIES.find(c=>c.id===b)?.label||b;
    return la.localeCompare(lb,"ko",{sensitivity:"base"});
  });
}

/* ===== GLOBAL CSS ===== */
const CSS = `
@keyframes fadeUp{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}
.ccel-fade{animation:fadeUp .3s ease both}
.ccel-card{transition:box-shadow .2s,transform .15s}
.ccel-card:hover{box-shadow:${C.shadowHover};transform:translateY(-1px)}
.ccel-pill{transition:all .12s;cursor:pointer;user-select:none}
.ccel-pill:hover{opacity:.85}
.ccel-search:focus{border-color:${C.accent}!important;box-shadow:0 0 0 3px ${C.accentSoft}!important}
.ccel-tab{position:relative}
.ccel-tab::after{content:'';position:absolute;bottom:-1px;left:50%;width:0;height:2px;background:${C.accent};transition:all .2s;transform:translateX(-50%)}
.ccel-tab[data-active="true"]::after{width:100%}
.ccel-landscape-section{scroll-margin-top:72px}
*{box-sizing:border-box}
body{margin:0;padding:0}
`;

function useStyles(){
  useEffect(()=>{
    if(document.getElementById("ccel-css"))return;
    const s=document.createElement("style");s.id="ccel-css";s.textContent=CSS;document.head.appendChild(s);
  },[]);
}

/* ===== DATA LOADING ===== */
function useNewsData(){
  const [data,setData]=useState(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState(null);

  useEffect(()=>{
    const paths = ["./data/news.json", "/data/news.json", "../backend/data/news.json"];
    let found = false;

    async function tryLoad(){
      for(const p of paths){
        try{
          const r=await fetch(p);
          if(r.ok){
            const d=await r.json();
            setData(d);
            found=true;
            break;
          }
        }catch(e){}
      }
      if(!found) setError("news.json not found. Run the backend pipeline first.");
      setLoading(false);
    }
    tryLoad();
  },[]);

  return {data,loading,error};
}

/* ===== COMPONENTS ===== */
function CLine(){return <div style={{width:50,height:2,background:C.accent,margin:"8px auto 0"}}/>}

function Badge({label,color}){
  return <span style={{display:"inline-block",padding:"2px 9px",borderRadius:2,fontSize:11,fontWeight:600,lineHeight:"18px",color,background:color+"12"}}>{label}</span>;
}

function Pill({label,active,color,onClick}){
  return <button className="ccel-pill" onClick={onClick} style={{
    padding:"5px 14px",borderRadius:3,border:active?`1.5px solid ${color||C.accent}`:`1px solid ${C.border}`,
    background:active?(color||C.accent)+"12":"transparent",color:active?(color||C.accent):C.gray600,
    fontSize:12.5,fontWeight:active?700:400,fontFamily:"inherit",
  }}>{label}</button>;
}

function Stat({value,label,color,title}){
  return <div style={{textAlign:"center",padding:"10px 0"}} title={title}>
    <div style={{fontSize:26,fontWeight:800,color,lineHeight:1}}>{value}</div>
    <div style={{fontSize:11,color:C.gray500,marginTop:4}}>{label}</div>
  </div>;
}

/** YYYY-MM-DD only; returns null if invalid */
function paperDateYmd(p){
  const raw=(p?.date||p?.updated||"").trim().slice(0,10);
  return /^\d{4}-\d{2}-\d{2}$/.test(raw)?raw:null;
}

/** As-of date for collection stats: feed snapshot date, then generated_at, then today */
function getCollectionAsOfYmd(data){
  const d=data?.date;
  if(typeof d==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(d))return d;
  const ga=data?.generated_at;
  if (typeof ga==="string"&&ga.length>=10){
    const s=ga.slice(0,10);
    if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;
  }
  const n=new Date();
  const y=n.getFullYear();
  const m=String(n.getMonth()+1).padStart(2,"0");
  const day=String(n.getDate()).padStart(2,"0");
  return `${y}-${m}-${day}`;
}

/** Subtract n days in local calendar (noon anchor) → YYYY-MM-DD */
function ymdMinusDays(ymd,nDays){
  const [y,mo,da]=ymd.split("-").map(Number);
  const dt=new Date(y,mo-1,da,12,0,0);
  dt.setDate(dt.getDate()-nDays);
  const yy=dt.getFullYear();
  const mm=String(dt.getMonth()+1).padStart(2,"0");
  const dd=String(dt.getDate()).padStart(2,"0");
  return `${yy}-${mm}-${dd}`;
}

const RELEVANCE_TOOLTIP = `Relevance (0–100): Google Gemini가 제목·초록·요약을 바탕으로 CCEL 연구와의 관련성을 산정합니다. 단순 키워드 매칭이 아닙니다.

점수 구간(파이프라인 기준):
• 95–100 — CCEL의 활성 연구 주제와 직접 연관
• 80–94 — 방법론·응용 분야에서 매우 높은 관련성
• 60–79 — 관련 분야, 배경으로 유용
• 40–59 — 간접적 연관
• 0–39 — 관련성 낮음`;

function NewsCard({d,bm,onBm,groups}){
  const cats = getSortedPaperCatIds(d);
  const grp=d.group?(groups||DEFAULT_GROUPS).find(g=>g.id===d.group):null;
  const isCcel=d.ccel||d.group==="ccel";
  const summary=d.summary||d.abstract||"";
  const rel=d.relevance||d.rel||0;
  const authors=d.authors_str||d.auth||(d.authors||[]).join("; ")||"";
  const date=d.date||"";

  return <article className="ccel-card ccel-fade" style={{
    background:C.white,borderLeft:isCcel?`4px solid ${C.accent}`:`1px solid ${C.borderLight}`,
    borderTop:`1px solid ${C.borderLight}`,borderRight:`1px solid ${C.borderLight}`,borderBottom:`1px solid ${C.borderLight}`,
    padding:"18px 20px",position:"relative",
  }}>
    {isCcel&&<span style={{position:"absolute",top:0,right:16,background:C.accent,color:C.white,fontSize:9.5,fontWeight:700,padding:"3px 8px 4px",borderRadius:"0 0 3px 3px",letterSpacing:.6,textTransform:"uppercase"}}>CCEL Group</span>}
    <div style={{display:"flex",alignItems:"center",gap:5,flexWrap:"wrap",marginBottom:8}}>
      {cats.map(catId => {
        const catDef = CATEGORIES.find(c=>c.id===catId);
        const color = cc(catId);
        const label = catDef ? catDef.label : catId;
        return <Badge key={catId} label={label} color={color}/>;
      })}
      {grp&&!isCcel&&<Badge label={grp.name} color={C.accent}/>}
      <span style={{fontSize:11,color:C.gray500}}>{d.source||""}</span>
      <span style={{fontSize:11,color:C.gray500}}>{date}</span>
      <div style={{marginLeft:"auto",display:"flex",alignItems:"center",gap:6}}>
        {rel>0&&<span title={RELEVANCE_TOOLTIP} style={{fontSize:10,fontWeight:600,color:rel>=95?C.accent:C.gray500,background:rel>=95?C.accentSoft:"transparent",padding:"1px 7px",borderRadius:2,cursor:"help",}}>Relevance {rel}</span>}
        <button onClick={()=>onBm(d.doi||d.title)} style={{background:"none",border:"none",cursor:"pointer",padding:0,fontSize:16,color:bm?C.ccelGold:C.gray300,transition:"color .15s"}}>{bm?"\u2605":"\u2606"}</button>
      </div>
    </div>
    <h3 style={{fontSize:15,fontWeight:700,color:C.textDark,margin:"0 0 3px",lineHeight:1.45,paddingRight:isCcel?80:0}}>{d.title||""}</h3>
    <p style={{fontSize:12,color:C.gray500,margin:"0 0 8px"}}>{authors}</p>
    <p style={{fontSize:13.5,color:C.textBody,margin:0,lineHeight:1.72}}>{summary}</p>
    {d.url&&<a href={d.url} target="_blank" rel="noopener noreferrer" style={{fontSize:12,color:C.accent,textDecoration:"none",display:"inline-block",marginTop:8}}>View paper &rarr;</a>}
  </article>;
}

function TrendChart({papers}){
  const byMonth={};
  const byCat={};
  (papers||[]).forEach(p=>{
    const d=p.date||"";
    const m=d.slice(0,7);
    const cats = getPaperCats(p);
    if(!m)return;
    cats.forEach(cat => {
      if(!byMonth[m])byMonth[m]={};
      byMonth[m][cat]=(byMonth[m][cat]||0)+1;
      byCat[cat]=(byCat[cat]||0)+1;
    });
  });

  const months=Object.keys(byMonth).sort().slice(-6);
  const topCats=Object.entries(byCat).sort((a,b)=>b[1]-a[1]).slice(0,5).map(e=>e[0]);

  if(months.length===0)return <div style={{padding:20,color:C.gray500,textAlign:"center"}}>Not enough data for trend chart.</div>;

  const W=600,H=210,PL=45,PR=30,PT=18,PB=30;
  const cW=W-PL-PR,cH=H-PT-PB;
  let mx=1;
  months.forEach(m=>{topCats.forEach(c=>{const v=(byMonth[m]||{})[c]||0;if(v>mx)mx=v;});});
  const sx=months.length>1?cW/(months.length-1):cW;

  const niceStep=(v)=>{const raw=v/4;const mag=Math.pow(10,Math.floor(Math.log10(raw)));const r=raw/mag;return(r<=1?1:r<=2?2:r<=5?5:10)*mag;};
  const step=niceStep(mx);
  const yTicks=[];
  for(let v=0;v<=mx;v+=step)yTicks.push(v);
  if(yTicks[yTicks.length-1]<mx)yTicks.push(yTicks[yTicks.length-1]+step);

  return <div className="ccel-card" style={{background:C.white,border:`1px solid ${C.borderLight}`,padding:20,boxShadow:C.shadow}}>
    <h4 style={{fontSize:15,fontWeight:700,color:C.textDark,margin:"0 0 2px"}}>Topic Distribution</h4>
    <p style={{fontSize:11,color:C.gray500,margin:"0 0 12px"}}>Papers by category</p>
    <svg viewBox={`0 0 ${W} ${H}`} width="100%">
      {yTicks.map(v=>{
        const y=PT+cH*(1-v/mx);
        return <g key={`yt-${v}`}>
          <line x1={PL} y1={y} x2={W-PR} y2={y} stroke={C.gray200||"#e5e7eb"} strokeWidth=".5" strokeDasharray="4 3"/>
          <text x={PL-6} y={y+3.5} textAnchor="end" style={{fontSize:9,fill:C.gray500}}>{v}</text>
        </g>;
      })}
      {months.map((m,i)=><text key={m} x={PL+i*sx} y={H-6} textAnchor="middle" style={{fontSize:10,fill:C.gray500}}>{m}</text>)}
      {topCats.map(cat=>{
        const pts=months.map((m,i)=>[PL+i*sx,PT+cH*(1-((byMonth[m]||{})[cat]||0)/mx)]);
        const d=pts.map((p,i)=>`${i===0?"M":"L"}${p[0]} ${p[1]}`).join(" ");
        const last=pts[pts.length-1];
        return <g key={cat}>
          <path d={d} fill="none" stroke={cc(cat)} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
          <circle cx={last[0]} cy={last[1]} r="3.5" fill={cc(cat)}/>
        </g>;
      })}
    </svg>
    <div style={{display:"flex",flexWrap:"wrap",gap:"10px 16px",marginTop:8}}>
      {topCats.map(c=><div key={c} style={{display:"flex",alignItems:"center",gap:5}}>
        <span style={{width:14,height:3,borderRadius:1,background:cc(c),display:"inline-block"}}/>
        <span style={{fontSize:11,color:C.gray600}}>{CATEGORIES.find(x=>x.id===c)?.label||c}</span>
      </div>)}
    </div>
  </div>;
}

function SourceBreakdown({papers}){
  const sources={};
  (papers||[]).forEach(p=>{const s=normalizeSource(p.source||"Unknown");sources[s]=(sources[s]||0)+1;});
  const sorted=Object.entries(sources).sort((a,b)=>b[1]-a[1]);
  const top=sorted.slice(0,30);
  const othersCount=sorted.slice(30).reduce((acc,[,n])=>acc+n,0);
  const rows=othersCount>0?[...top,["Others",othersCount]]:top;
  const mx=rows.length?Math.max(...rows.map(([,n])=>n)):1;

  return <div className="ccel-card" style={{background:C.white,border:`1px solid ${C.borderLight}`,padding:20,boxShadow:C.shadow}}>
    <h4 style={{fontSize:15,fontWeight:700,color:C.textDark,margin:"0 0 2px"}}>Source Breakdown</h4>
    <p style={{fontSize:11,color:C.gray500,margin:"0 0 14px"}}>Papers by journal (top 30 + Others)</p>
    <div style={{display:"flex",flexDirection:"column",gap:8}}>
      {rows.map(([s,n])=><div key={s} style={{display:"flex",alignItems:"center",gap:12}}>
        <div style={{width:140,flexShrink:0,fontSize:12,fontWeight:500,color:C.textDark,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{s}</div>
        <div style={{flex:1,height:14,background:C.gray100,borderRadius:2,overflow:"hidden"}}>
          <div style={{width:`${(n/mx)*100}%`,height:"100%",background:C.accent,opacity:.6,borderRadius:2}}/>
        </div>
        <span style={{fontSize:12,fontWeight:700,color:C.textDark,width:28,textAlign:"right"}}>{n}</span>
      </div>)}
    </div>
  </div>;
}

function CategoryTrends({trends}){
  const [activeCat,setActiveCat]=useState(null);
  const [timeView,setTimeView]=useState("monthly");

  if(!trends||Object.keys(trends).length===0) return null;

  const catOrder=["dft","catalysis","electrochemistry","battery","ml","policy"];
  const available=catOrder.filter(c=>trends[c]);

  const current=activeCat&&trends[activeCat]?activeCat:available[0];
  if(!current)return null;
  const t=trends[current];
  const digest=timeView==="monthly"
    ?(t.digest_monthly||t.digest||t)
    :(t.digest_yearly||t.digest||t);
  const color=cc(current);
  const paperCount=timeView==="monthly"?t.paper_count_monthly:t.paper_count_yearly;

  return <div className="ccel-card" style={{background:C.white,border:`1px solid ${C.borderLight}`,padding:0,boxShadow:C.shadow,overflow:"hidden"}}>
    <div style={{padding:"16px 20px 0",borderBottom:`1px solid ${C.borderLight}`}}>
      <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:12}}>
        <div style={{width:30,height:30,borderRadius:3,background:C.textDark,display:"flex",alignItems:"center",justifyContent:"center",color:C.white,fontSize:10,fontWeight:800,flexShrink:0}}>AI</div>
        <div style={{flex:1}}>
          <h4 style={{fontSize:15,fontWeight:700,margin:0,color:C.textDark}}>Category Research Digests</h4>
          <p style={{fontSize:11,color:C.gray500,margin:0}}>AI-generated analysis per research area</p>
        </div>
        <div style={{display:"flex",background:C.bg,borderRadius:6,padding:2,gap:0}}>
          {[{id:"monthly",label:"Monthly"},{id:"yearly",label:"Yearly"}].map(v=>
            <button key={v.id} onClick={()=>setTimeView(v.id)} style={{
              padding:"5px 12px",border:"none",borderRadius:5,cursor:"pointer",fontFamily:"inherit",
              fontSize:11,fontWeight:v.id===timeView?700:400,
              background:v.id===timeView?C.white:"transparent",
              color:v.id===timeView?C.textDark:C.gray500,
              boxShadow:v.id===timeView?"0 1px 3px rgba(0,0,0,.1)":"none",
              transition:"all .15s",
            }}>{v.label}</button>
          )}
        </div>
      </div>

      <div style={{display:"flex",gap:0,overflowX:"auto"}}>
        {available.map(catId=>{
          const label=CATEGORIES.find(c=>c.id===catId)?.label||catId;
          const catColor=cc(catId);
          const isActive=catId===current;
          const count=timeView==="monthly"?trends[catId]?.paper_count_monthly:trends[catId]?.paper_count_yearly;
          return <button key={catId} onClick={()=>setActiveCat(catId)} style={{
            padding:"8px 14px",border:"none",borderBottom:isActive?`2.5px solid ${catColor}`:"2.5px solid transparent",
            background:"transparent",cursor:"pointer",fontFamily:"inherit",fontSize:11.5,
            fontWeight:isActive?700:400,color:isActive?catColor:C.gray500,transition:"all .15s",whiteSpace:"nowrap",
          }}>
            {label} <span style={{fontSize:10,opacity:.7}}>({count||0})</span>
          </button>;
        })}
      </div>
    </div>

    <div style={{padding:"0"}}>
      <div style={{padding:"12px 20px 0",display:"flex",alignItems:"center",gap:8}}>
        <span style={{fontSize:11,color:C.gray500}}>{timeView==="monthly"?"Monthly":"Yearly"}: {paperCount} papers</span>
        {digest.depth&&<span style={{fontSize:10,color,marginLeft:"auto",fontWeight:600,textTransform:"uppercase"}}>{digest.depth}</span>}
      </div>
      <StructuredDigestContent digest={digest} accentColor={color}/>
    </div>
  </div>;
}

function StructuredDigestContent({digest,accentColor}){
  const color=accentColor||C.accent;
  if(!digest)return null;

  if(digest.depth==="skip"){
    return <div style={{padding:"20px",textAlign:"center",color:C.gray500}}>
      <p style={{fontSize:13,margin:0}}>논문이 충분히 축적되면 AI 분석이 제공됩니다.</p>
    </div>;
  }

  const hotIssues=digest.hot_issues||[];
  const sections=digest.sections||[];
  const notablePapers=digest.notable_papers||[];
  if(hotIssues.length===0&&sections.length===0&&notablePapers.length===0)return null;

  return <>
    {hotIssues.length>0&&<div style={{padding:"14px 20px",background:color+"08",borderBottom:`1px solid ${C.borderLight}`}}>
      <div style={{fontSize:11,fontWeight:700,color,textTransform:"uppercase",letterSpacing:1,marginBottom:8}}>Hot Issues</div>
      <div style={{display:"flex",flexDirection:"column",gap:8}}>
        {hotIssues.map((issue,i)=><div key={i} style={{display:"flex",gap:10,alignItems:"flex-start"}}>
          <span style={{flexShrink:0,width:22,height:22,borderRadius:3,background:color,color:C.white,fontSize:11,fontWeight:700,display:"flex",alignItems:"center",justifyContent:"center"}}>{i+1}</span>
          <div>
            <span style={{fontSize:13,fontWeight:700,color:C.textDark}}>{issue.topic}</span>
            <p style={{fontSize:12.5,color:C.textBody,margin:"2px 0 0",lineHeight:1.6}}>{issue.description}</p>
          </div>
        </div>)}
      </div>
    </div>}

    <div style={{padding:"16px 20px"}}>
      {sections.map((sec,i)=>{
        if(!sec.content)return null;
        return <div key={i} style={{marginBottom:i<sections.length-1?18:0}}>
          <h5 style={{fontSize:13.5,fontWeight:700,color:C.textDark,margin:"0 0 6px",borderLeft:`3px solid ${color}`,paddingLeft:10}}>{sec.title}</h5>
          {sec.content.split("\n\n").map((p,j)=><p key={j} style={{fontSize:13,color:C.textBody,lineHeight:1.72,margin:j===0?0:"8px 0 0",paddingLeft:13}}>{p}</p>)}
        </div>;
      })}

      {notablePapers.length>0&&<div style={{marginTop:sections.length>0?14:0,borderTop:sections.length>0?`1px solid ${C.borderLight}`:"none",paddingTop:sections.length>0?12:0}}>
        <div style={{fontSize:11,fontWeight:700,color:C.gray600,textTransform:"uppercase",letterSpacing:1,marginBottom:8}}>Notable Papers</div>
        {notablePapers.map((np,i)=><div key={i} style={{marginBottom:8,paddingLeft:10,borderLeft:`2px solid ${color}30`}}>
          <div style={{fontSize:12.5,fontWeight:600,color:C.textDark,lineHeight:1.4}}>{np.title}</div>
          <div style={{fontSize:12,color:C.gray600,marginTop:2,lineHeight:1.5}}>{np.reason}</div>
        </div>)}
      </div>}

      {digest.generated_at&&<p style={{fontSize:10,color:C.gray300,marginTop:12,textAlign:"right"}}>
        Generated: {digest.generated_at.slice(0,10)}
      </p>}
    </div>
  </>;
}

function WeeklyDigest({digest}){
  if(!digest)return null;

  if(typeof digest==="string"){
    if(!digest)return null;
    return <div className="ccel-card" style={{background:C.white,border:`1px solid ${C.borderLight}`,borderLeft:`4px solid ${C.accent}`,padding:20,boxShadow:C.shadow}}>
      <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:14}}>
        <div style={{width:30,height:30,borderRadius:3,background:C.accent,display:"flex",alignItems:"center",justifyContent:"center",color:C.white,fontSize:11,fontWeight:800,flexShrink:0}}>AI</div>
        <div>
          <h4 style={{fontSize:15,fontWeight:700,margin:0,color:C.textDark}}>Weekly Digest</h4>
          <p style={{fontSize:11,color:C.gray500,margin:0}}>Auto-generated by Gemini</p>
        </div>
      </div>
      {digest.split("\n\n").map((p,i)=><p key={i} style={{fontSize:13.5,color:C.textBody,lineHeight:1.75,margin:i===0?0:"10px 0 0"}}>{p}</p>)}
    </div>;
  }

  const sections=digest.sections||[];
  const hotIssues=digest.hot_issues||[];
  if(sections.length===0&&hotIssues.length===0)return null;

  return <div className="ccel-card" style={{background:C.white,border:`1px solid ${C.borderLight}`,padding:0,boxShadow:C.shadow,overflow:"hidden"}}>
    <div style={{padding:"16px 20px",borderBottom:`1px solid ${C.borderLight}`,display:"flex",alignItems:"center",gap:10}}>
      <div style={{width:30,height:30,borderRadius:3,background:C.accent,display:"flex",alignItems:"center",justifyContent:"center",color:C.white,fontSize:11,fontWeight:800,flexShrink:0}}>AI</div>
      <div>
        <h4 style={{fontSize:15,fontWeight:700,margin:0,color:C.textDark}}>Weekly Digest</h4>
        <p style={{fontSize:11,color:C.gray500,margin:0}}>Auto-generated by Gemini{digest.generated_at?` · ${digest.generated_at.slice(0,10)}`:""}</p>
      </div>
    </div>
    <StructuredDigestContent digest={digest} accentColor={C.accent}/>
  </div>;
}

function GroupDigests({groupDigests}){
  const [activeGroup,setActiveGroup]=useState(null);

  if(!groupDigests||Object.keys(groupDigests).length===0)return null;

  const available=[...Object.keys(groupDigests)].sort((a,b)=>{
    if(a==="ccel")return-1;
    if(b==="ccel")return 1;
    const na=(groupDigests[a].group_name||a).toLowerCase();
    const nb=(groupDigests[b].group_name||b).toLowerCase();
    return na.localeCompare(nb);
  });
  const current=activeGroup&&groupDigests[activeGroup]?activeGroup:available[0];
  if(!current)return null;
  const gd=groupDigests[current];
  const digest=gd.digest||gd;

  return <div className="ccel-card" style={{background:C.white,border:`1px solid ${C.borderLight}`,padding:0,boxShadow:C.shadow,overflow:"hidden"}}>
    <div style={{padding:"16px 20px",borderBottom:`1px solid ${C.borderLight}`}}>
      <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:12}}>
        <div style={{width:30,height:30,borderRadius:3,background:C.textDark,display:"flex",alignItems:"center",justifyContent:"center",color:C.white,fontSize:9,fontWeight:800,flexShrink:0}}>GRP</div>
        <div>
          <h4 style={{fontSize:15,fontWeight:700,margin:0,color:C.textDark}}>Group Research Digests</h4>
          <p style={{fontSize:11,color:C.gray500,margin:0}}>Per-group research direction analysis</p>
        </div>
      </div>

      <div style={{display:"flex",gap:5,flexWrap:"wrap"}}>
        {available.map(gid=>{
          const g=groupDigests[gid];
          const isActive=gid===current;
          return <Pill key={gid} label={`${g.group_name} (${g.paper_count})`} active={isActive} color={C.accent} onClick={()=>setActiveGroup(gid)}/>;
        })}
      </div>
    </div>

    <div style={{padding:"0"}}>
      <div style={{padding:"12px 20px 0",display:"flex",alignItems:"center",gap:8}}>
        <span style={{fontSize:14,fontWeight:700,color:C.textDark}}>{gd.group_name}</span>
        {gd.pi&&<span style={{fontSize:12,color:C.gray500}}>PI: {gd.pi}</span>}
        <span style={{fontSize:11,color:C.gray500,marginLeft:"auto"}}>{gd.paper_count} papers</span>
      </div>
      <StructuredDigestContent digest={digest} accentColor={C.accent}/>
    </div>
  </div>;
}

/* ===== MAIN APP ===== */
export default function App(){
  useStyles();
  const {data,loading,error}=useNewsData();
  const [view,setView]=useState("landscape");
  const [selectedCats,setSelectedCats]=useState(new Set()); // multi-select categories (AND logic)
  const [grps,setGrps]=useState(new Set());
  const [selectedJournals,setSelectedJournals]=useState(new Set());
  const [q,setQ]=useState("");
  const [bms,setBms]=useState(new Set());
  const [bmOnly,setBmOnly]=useState(false);
  const [sort,setSort]=useState("latest");
  const [showRelevanceInfo,setShowRelevanceInfo]=useState(false);
  const [page,setPage]=useState(1);
  const searchRef=useRef(null);
  const PER_PAGE=20;

  useEffect(()=>{
    const h=e=>{if(e.key==="/"&&document.activeElement?.tagName!=="INPUT"){e.preventDefault();searchRef.current?.focus();}};
    window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h);
  },[]);

  // Reset page on filter change
  useEffect(()=>{setPage(1);},[selectedCats,grps,selectedJournals,q,bmOnly,sort,view]);

  const toggleCat=id=>{
    setSelectedCats(prev=>{
      const n=new Set(prev);
      if(n.has(id)) n.delete(id); else n.add(id);
      return n;
    });
  };
  const toggleGrp=id=>setGrps(p=>{const n=new Set(p);n.has(id)?n.delete(id):n.add(id);return n;});
  const toggleJournal=id=>setSelectedJournals(p=>{const n=new Set(p);n.has(id)?n.delete(id):n.add(id);return n;});
  const toggleBm=id=>setBms(p=>{const n=new Set(p);n.has(id)?n.delete(id):n.add(id);return n;});

  const papers=data?.papers||[];
  const paperCollectionStats=useMemo(()=>{
    const total=papers.length;
    const asOf=getCollectionAsOfYmd(data);
    const min30=ymdMinusDays(asOf,30);
    const min365=ymdMinusDays(asOf,365);
    let count30=0,count365=0;
    for(const p of papers){
      const pd=paperDateYmd(p);
      if(!pd)continue;
      if(pd>asOf)continue;
      if(pd>=min30)count30++;
      if(pd>=min365)count365++;
    }
    return{count30,count365,total,asOf,min30,min365};
  },[papers,data]);
  const allGroups=data?.groups||DEFAULT_GROUPS;
  const digest=data?.weekly_digest||null;
  const categoryTrends=data?.category_trends||{};
  const groupDigests=data?.group_digests||{};
  const genDate=data?.date||data?.generated_at?.slice(0,10)||"";

  const topJournals=useMemo(()=>{
    const cnt={};
    papers.forEach(p=>{const s=normalizeSource(p.source||"Unknown");cnt[s]=(cnt[s]||0)+1;});
    return Object.entries(cnt).sort((a,b)=>b[1]-a[1]).slice(0,30).map(([name,count])=>({name,count}));
  },[papers]);

  const filtered=useMemo(()=>{
    return papers.filter(d=>{
      const dCats = getPaperCats(d);

      // AND logic: paper must contain ALL selected categories
      if(selectedCats.size>0){
        for(const sc of selectedCats){
          if(!dCats.includes(sc)) return false;
        }
      }

      if(grps.size>0&&!grps.has(d.group))return false;
      if(selectedJournals.size>0&&!selectedJournals.has(normalizeSource(d.source||"Unknown")))return false;
      if(bmOnly&&!bms.has(d.doi||d.title))return false;
      if(q){
        const s=q.toLowerCase();
        return (d.title||"").toLowerCase().includes(s)||(d.summary||d.abstract||"").toLowerCase().includes(s)||(d.authors_str||"").toLowerCase().includes(s);
      }
      return true;
    }).sort((a,b)=>{
      if(sort==="relevance")return (b.relevance||b.rel||0)-(a.relevance||a.rel||0);
      if(sort==="latest")return (a.date||"")<(b.date||"")?1:-1;
      if(sort==="oldest")return (a.date||"")>(b.date||"")?1:-1;
      if(sort==="title")return (a.title||"").localeCompare(b.title||"","ko",{sensitivity:"base"});
      return 0;
    });
  },[papers,selectedCats,grps,selectedJournals,bmOnly,bms,q,sort]);

  const paged=filtered.slice(0,page*PER_PAGE);
  const hasMore=paged.length<filtered.length;

  const tabs=[{id:"landscape",label:"Research Landscape"},{id:"feed",label:"Paper Feed"},{id:"milestones",label:"Milestones"}];

  if(loading)return <div style={{fontFamily:"'Noto Sans KR',sans-serif",display:"flex",justifyContent:"center",alignItems:"center",height:"100vh",color:C.gray500}}>Loading...</div>;
  if(error)return <div style={{fontFamily:"'Noto Sans KR',sans-serif",display:"flex",justifyContent:"center",alignItems:"center",height:"100vh",color:C.gray500,flexDirection:"column",gap:8}}><div>{error}</div><div style={{fontSize:12}}>Place news.json in public/data/</div></div>;

  // Count for active filter display
  const activeFilterCount = selectedCats.size;

  return <div style={{fontFamily:"'Noto Sans KR',-apple-system,BlinkMacSystemFont,sans-serif",background:C.white,minHeight:"100vh"}}>
    <link href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css" rel="stylesheet"/>

    {/* Navbar */}
    <nav style={{background:C.white,borderBottom:`1px solid ${C.border}`,position:"sticky",top:0,zIndex:100,boxShadow:"0 1px 3px rgba(0,0,0,0.04)"}}>
      <div style={{maxWidth:980,margin:"0 auto",padding:"0 20px",display:"flex",alignItems:"center",height:54}}>
        <div style={{display:"flex",alignItems:"baseline",gap:8,marginRight:32}}>
          <span style={{fontSize:20,fontWeight:800,color:C.textDark,letterSpacing:-.8}}>CCEL</span>
          <span style={{fontSize:12,color:C.gray500,fontWeight:400,letterSpacing:.5}}>WEEKLY NEWS</span>
        </div>
        <div style={{display:"flex",gap:2,height:"100%"}}>
          {tabs.map(t=><button key={t.id} className="ccel-tab" data-active={view===t.id} title={t.id==="milestones"?"곧 제공될 예정입니다":undefined} onClick={()=>setView(t.id)} style={{
            padding:"0 18px",border:"none",cursor:"pointer",fontFamily:"inherit",fontSize:13,fontWeight:view===t.id?700:400,height:"100%",background:"transparent",color:view===t.id?C.accent:C.gray600,transition:"color .15s",display:"flex",alignItems:"center",gap:6,
          }}>{t.label}{t.id==="milestones"&&<span style={{fontSize:9,fontWeight:700,color:C.gray500,background:C.gray100,padding:"2px 5px",borderRadius:2,letterSpacing:0}}>준비 중</span>}</button>)}
        </div>
        <div style={{marginLeft:"auto",fontSize:12,color:C.gray500}}>{genDate}</div>
      </div>
    </nav>

    {/* Hero */}
    <div style={{background:C.bg,padding:"22px 20px",borderBottom:`1px solid ${C.border}`}}>
      <div style={{maxWidth:980,margin:"0 auto",textAlign:"center"}}>
        <h1 style={{fontSize:18,fontWeight:700,color:C.textDark,margin:"0 0 4px",letterSpacing:-.3}}>Computational Catalysis and Emerging Materials Laboratory</h1>
        <p style={{fontSize:12.5,color:C.gray600,margin:0}}>Seoul National University | Prof. Jeong Woo Han</p>
      </div>
    </div>

    {/* Main */}
    <div style={{maxWidth:980,margin:"0 auto",padding:"20px 20px 0"}}>

      {view==="feed"&&<div style={{background:C.bgAlt,border:`1px solid ${C.borderLight}`,padding:"14px 16px",marginBottom:22}}>
        <div style={{marginBottom:10}}>
          <span style={{fontSize:10.5,color:C.gray500,fontWeight:600,textTransform:"uppercase",letterSpacing:1}}>Groups</span>
          <div style={{display:"flex",gap:5,flexWrap:"wrap",marginTop:5}}>
            {[...allGroups].sort((a,b)=>a.name.localeCompare(b.name)).map(g=><Pill key={g.id} label={g.name} active={grps.has(g.id)} color={C.accent} onClick={()=>toggleGrp(g.id)}/>)}
          </div>
        </div>
        <div style={{marginBottom:10}}>
          <div style={{display:"flex",alignItems:"center",gap:8}}>
            <span style={{fontSize:10.5,color:C.gray500,fontWeight:600,textTransform:"uppercase",letterSpacing:1}}>Categories</span>
            {activeFilterCount>=2&&<span style={{fontSize:10,color:C.accent,fontWeight:600}}>AND filter ({activeFilterCount} selected)</span>}
            {activeFilterCount>0&&<button onClick={()=>setSelectedCats(new Set())} style={{fontSize:10,color:C.gray500,background:"none",border:"none",cursor:"pointer",fontFamily:"inherit",textDecoration:"underline",padding:0}}>Clear</button>}
          </div>
          <div style={{display:"flex",gap:5,flexWrap:"wrap",marginTop:5}}>
            {CATEGORIES.map(c=><Pill key={c.id} label={c.label} active={selectedCats.has(c.id)} color={cc(c.id)} onClick={()=>toggleCat(c.id)}/>)}
          </div>
        </div>
        <div>
          <div style={{display:"flex",alignItems:"center",gap:8}}>
            <span style={{fontSize:10.5,color:C.gray500,fontWeight:600,textTransform:"uppercase",letterSpacing:1}}>Journals</span>
            {selectedJournals.size>0&&<span style={{fontSize:10,color:C.accent,fontWeight:600}}>{selectedJournals.size} selected</span>}
            {selectedJournals.size>0&&<button onClick={()=>setSelectedJournals(new Set())} style={{fontSize:10,color:C.gray500,background:"none",border:"none",cursor:"pointer",fontFamily:"inherit",textDecoration:"underline",padding:0}}>Clear</button>}
          </div>
          <div style={{display:"flex",gap:5,flexWrap:"wrap",marginTop:5}}>
            {[...topJournals].sort((a,b)=>a.name.localeCompare(b.name)).map(j=><Pill key={j.name} label={`${j.name} (${j.count})`} active={selectedJournals.has(j.name)} color="#6C5CE7" onClick={()=>toggleJournal(j.name)}/>)}
          </div>
        </div>
      </div>}

      {/* PAPER FEED */}
      {view==="feed"&&<div>
        <div style={{textAlign:"center",marginBottom:20}}>
          <h2 style={{fontSize:20,fontWeight:700,color:C.textDark,margin:0}}>Paper Feed</h2>
          <CLine/>
        </div>

        <div style={{
          background:C.white,border:`1px solid ${C.borderLight}`,marginBottom:16,boxShadow:C.shadow,
          display:"grid",gridTemplateColumns:"repeat(3, 1fr)",maxWidth:720,marginLeft:"auto",marginRight:"auto",
        }}>
          <Stat
            value={paperCollectionStats.count30}
            label="Last 30 days"
            color={C.accent}
            title={`Papers dated between ${paperCollectionStats.min30} and ${paperCollectionStats.asOf} (rolling 30 days). Undated papers are excluded.`}
          />
          <Stat
            value={paperCollectionStats.count365}
            label="Last 365 days"
            color={C.accent}
            title={`Papers dated between ${paperCollectionStats.min365} and ${paperCollectionStats.asOf} (rolling 365 days). Undated papers are excluded.`}
          />
          <Stat
            value={paperCollectionStats.total}
            label="Total"
            color={C.accent}
            title="All papers in this feed snapshot."
          />
        </div>

        {(grps.size>0||selectedCats.size>0||selectedJournals.size>0||bmOnly)&&<div style={{display:"flex",flexWrap:"wrap",gap:6,alignItems:"center",marginBottom:10}}>
          <span style={{fontSize:10.5,color:C.gray500,fontWeight:600,marginRight:4}}>활성 필터</span>
          {[...grps].map(id=>{
            const g=allGroups.find(x=>x.id===id);
            return <span key={`g-${id}`} style={{display:"inline-flex",alignItems:"center",gap:4,fontSize:11,padding:"3px 8px",borderRadius:3,background:C.accent+"14",color:C.accent,border:`1px solid ${C.accent}40`}}>
              {g?.name||id}
              <button type="button" onClick={()=>toggleGrp(id)} aria-label={`Remove ${g?.name||id}`} style={{background:"none",border:"none",cursor:"pointer",padding:0,fontSize:14,lineHeight:1,color:C.accent}}>×</button>
            </span>;
          })}
          {[...selectedCats].map(cid=>{
            const lab=CATEGORIES.find(c=>c.id===cid)?.label||cid;
            return <span key={`c-${cid}`} style={{display:"inline-flex",alignItems:"center",gap:4,fontSize:11,padding:"3px 8px",borderRadius:3,background:cc(cid)+"18",color:cc(cid),border:`1px solid ${cc(cid)}50`}}>
              {lab}
              <button type="button" onClick={()=>toggleCat(cid)} aria-label={`Remove ${lab}`} style={{background:"none",border:"none",cursor:"pointer",padding:0,fontSize:14,lineHeight:1,color:cc(cid)}}>×</button>
            </span>;
          })}
          {[...selectedJournals].map(jn=><span key={`j-${jn}`} style={{display:"inline-flex",alignItems:"center",gap:4,fontSize:11,padding:"3px 8px",borderRadius:3,background:"#6C5CE718",color:"#6C5CE7",border:"1px solid #6C5CE750"}}>
            {jn}
            <button type="button" onClick={()=>toggleJournal(jn)} aria-label={`Remove ${jn}`} style={{background:"none",border:"none",cursor:"pointer",padding:0,fontSize:14,lineHeight:1,color:"#6C5CE7"}}>×</button>
          </span>)}
          {bmOnly&&<span style={{display:"inline-flex",alignItems:"center",gap:4,fontSize:11,padding:"3px 8px",borderRadius:3,background:C.ccelGold+"18",color:C.ccelGold,border:`1px solid ${C.ccelGold}50`}}>
            Bookmarks
            <button type="button" onClick={()=>setBmOnly(false)} aria-label="Remove bookmarks filter" style={{background:"none",border:"none",cursor:"pointer",padding:0,fontSize:14,lineHeight:1,color:C.ccelGold}}>×</button>
          </span>}
        </div>}

        <input ref={searchRef} className="ccel-search" type="text" placeholder='Search papers, authors, keywords...  ("/" to focus)' value={q} onChange={e=>setQ(e.target.value)} style={{
          width:"100%",padding:"10px 14px",border:`1px solid ${C.border}`,background:C.white,color:C.textDark,fontSize:13,fontFamily:"inherit",outline:"none",marginBottom:12,
        }}/>

        <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:12,marginBottom:10,flexWrap:"wrap"}}>
          <div style={{display:"flex",flexDirection:"column",gap:8}}>
            <div style={{display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"}}>
              <span style={{fontSize:11,color:C.gray600,fontWeight:600}}>정렬</span>
              <div style={{display:"flex",gap:3,flexWrap:"wrap"}}>
                {[
                  ["latest","최신순"],
                  ["oldest","과거순"],
                  ["title","제목 A–Z"],
                  ["relevance","Relevance"],
                ].map(([k,l])=><button key={k} onClick={()=>setSort(k)} style={{
                  padding:"4px 10px",border:"none",fontFamily:"inherit",cursor:"pointer",fontSize:11.5,fontWeight:600,
                  background:sort===k?C.textDark:"transparent",color:sort===k?C.white:C.gray500,
                  borderRadius:3,
                }}>{l}</button>)}
              </div>
              <span style={{fontSize:11,color:C.gray500}}>{filtered.length} papers{(selectedCats.size>0||selectedJournals.size>0||grps.size>0)?` (filtered)`:""}</span>
            </div>
            <div>
              <button type="button" onClick={()=>setShowRelevanceInfo(v=>!v)} style={{
                fontSize:11,color:C.accent,background:"none",border:"none",cursor:"pointer",fontFamily:"inherit",padding:0,textDecoration:"underline",fontWeight:600,
              }}>{showRelevanceInfo?"▲ Relevance 점수 안내 닫기":"▼ Relevance 점수 안내"}</button>
              {showRelevanceInfo&&<div style={{
                marginTop:8,padding:"12px 14px",background:C.bgAlt,border:`1px solid ${C.borderLight}`,borderRadius:4,
                fontSize:12,color:C.textBody,lineHeight:1.65,maxWidth:640,
              }}>
                <p style={{margin:"0 0 8px",fontWeight:700,color:C.textDark}}>Relevance 점수는 어떻게 정해지나요?</p>
                <p style={{margin:0}}>각 논문에 대해 <strong>Google Gemini</strong>가 제목·초록·파이프라인에서 생성한 요약 텍스트를 읽고, <strong>CCEL(계산 촉매·신소재 연구실)의 관심 주제</strong>와 얼마나 맞는지 <strong>0~100의 수치</strong>로 평가합니다. 단순 키워드 빈도가 아니라, 아래 구간에 맞춰 <strong>정량적으로 한 점수</strong>를 부여하도록 파이프라인에서 안내합니다.</p>
                <p style={{margin:"10px 0 6px",fontWeight:700,color:C.textDark,fontSize:11.5}}>점수 구간 (summarizer 프롬프트 기준)</p>
                <ul style={{margin:0,paddingLeft:18,listStyle:"disc"}}>
                  <li><strong>95–100</strong> — CCEL의 활성 연구 주제와 직접 연관 (Directly related to CCEL&apos;s active research topics)</li>
                  <li><strong>80–94</strong> — 방법론·응용 분야에서 매우 높은 관련성 (Highly relevant methodology or application area)</li>
                  <li><strong>60–79</strong> — 관련 분야, 배경으로 유용 (Related field, useful background)</li>
                  <li><strong>40–59</strong> — 간접적 연관 (Tangentially related)</li>
                  <li><strong>0–39</strong> — 관련성 낮음 (Not very relevant)</li>
                </ul>
                <p style={{margin:"10px 0 0"}}>같은 구간 안에서도 논문마다 의미는 다를 수 있습니다. <strong>카테고리 태그</strong>(DFT, 촉매 등)는 별도 라벨입니다. 정렬에서 <strong>최신순·과거순·제목순</strong>은 날짜·제목만 쓰고, <strong>Relevance</strong>를 고를 때만 이 점수 순으로 정렬됩니다.</p>
              </div>}
            </div>
          </div>
          <button className="ccel-pill" onClick={()=>setBmOnly(!bmOnly)} style={{
            padding:"4px 12px",fontFamily:"inherit",border:bmOnly?`1.5px solid ${C.ccelGold}`:`1px solid ${C.border}`,
            background:bmOnly?C.ccelGold+"10":"transparent",color:bmOnly?C.ccelGold:C.gray500,
            fontSize:11.5,fontWeight:600,borderRadius:3,flexShrink:0,
          }}>{bmOnly?`\u2605 (${bms.size})`:"\u2606 Bookmarks"}</button>
        </div>

        <div style={{display:"flex",flexDirection:"column",gap:8}}>
          {paged.length===0?<div style={{textAlign:"center",padding:50,color:C.gray500,fontSize:13}}>No results.{selectedCats.size>=2?" Try removing a category filter.":""}</div>
            :paged.map((d,i)=><div key={d.doi||d.title||i} style={{animationDelay:`${Math.min(i,10)*0.03}s`}}><NewsCard d={d} bm={bms.has(d.doi||d.title)} onBm={toggleBm} groups={allGroups}/></div>)
          }
        </div>
        {hasMore&&<div style={{textAlign:"center",padding:"20px 0"}}>
          <button onClick={()=>setPage(p=>p+1)} style={{padding:"10px 32px",border:`1px solid ${C.border}`,background:C.white,color:C.textDark,fontSize:13,fontWeight:600,cursor:"pointer",fontFamily:"inherit",borderRadius:3}}>Load more ({filtered.length-paged.length} remaining)</button>
        </div>}
      </div>}

      {/* RESEARCH LANDSCAPE */}
      {view==="landscape"&&<div>
        <div style={{textAlign:"center",marginBottom:20}}>
          <h2 style={{fontSize:20,fontWeight:700,color:C.textDark,margin:0}}>Research Landscape</h2>
          <p style={{fontSize:13,color:C.gray500,margin:"4px 0 0"}}>Trends, source breakdown, and AI-powered analysis</p>
          <CLine/>
        </div>
        <nav style={{display:"flex",flexWrap:"wrap",gap:"8px 14px",justifyContent:"center",marginBottom:18,padding:"10px 12px",background:C.bgAlt,border:`1px solid ${C.borderLight}`,borderRadius:4}} aria-label="Research Landscape sections">
          {[
            ["#landscape-weekly-digest","Weekly Digest"],
            ["#landscape-group-digests","Group Research Digests"],
            ["#landscape-category-digests","Category Research Digests"],
            ["#landscape-topic-distribution","Topic Distribution"],
            ["#landscape-source-breakdown","Source Breakdown"],
          ].map(([href,lab])=><a key={href} href={href} style={{fontSize:12,color:C.accent,fontWeight:600,textDecoration:"none",borderBottom:`1px solid ${C.accent}40`}}>{lab}</a>)}
        </nav>
        <div style={{display:"flex",flexDirection:"column",gap:14}}>
          <div id="landscape-weekly-digest" className="ccel-landscape-section"><WeeklyDigest digest={digest}/></div>
          <div id="landscape-group-digests" className="ccel-landscape-section"><GroupDigests groupDigests={groupDigests}/></div>
          <div id="landscape-category-digests" className="ccel-landscape-section"><CategoryTrends trends={categoryTrends}/></div>
          <div id="landscape-topic-distribution" className="ccel-landscape-section"><TrendChart papers={papers}/></div>
          <div id="landscape-source-breakdown" className="ccel-landscape-section"><SourceBreakdown papers={papers}/></div>
        </div>
      </div>}

      {/* MILESTONES */}
      {view==="milestones"&&<div>
        <div style={{textAlign:"center",marginBottom:20}}>
          <h2 style={{fontSize:20,fontWeight:700,color:C.textDark,margin:0}}>Milestones</h2>
          <p style={{fontSize:13,color:C.gray500,margin:"4px 0 0"}}>Coming soon: curated landmark papers</p>
          <CLine/>
        </div>
        <div style={{textAlign:"center",padding:"60px 20px",color:C.gray500}}>
          <p style={{fontSize:14}}>Milestone papers will be curated by lab members.</p>
          <p style={{fontSize:12,marginTop:8}}>Once added, they will appear here as a timeline of key papers in each research area.</p>
        </div>
      </div>}
    </div>

    {/* Footer */}
    <footer style={{background:C.footerBg,padding:"28px 20px",marginTop:50,textAlign:"center"}}>
      <h3 style={{fontSize:14,fontWeight:600,color:C.white,margin:"0 0 6px"}}>Computational Catalysis and Emerging Materials Laboratory</h3>
      <p style={{fontSize:11,color:C.footerText,margin:"0 0 3px",lineHeight:1.6}}>Department of Materials Science and Engineering, Seoul National University<br/>1 Gwanak-ro, Gwanak-gu, Seoul 08826, Korea</p>
      <div style={{width:40,height:1,background:C.footerDim,margin:"12px auto"}}/>
      <p style={{fontSize:10.5,color:C.footerDim,margin:0}}>CCEL Weekly News | Powered by Gemini API + arXiv + RSS | Auto-updated via GitHub Actions</p>
    </footer>
  </div>;
}
