import { useState, useMemo, useEffect, useRef } from "react";

/*
 * CCEL Daily News - Production App
 * Loads data from /data/news.json (generated by backend)
 * Supports multi-category (categories array) with AND filter logic
 */

/* ===== DESIGN TOKENS ===== */
const C = {
  white: "#ffffff", bg: "#f2f2f2", bgAlt: "#fafafa",
  border: "#e5e5e5", borderLight: "#eeeeee",
  gray100: "#f7f7f7", gray300: "#cccccc", gray500: "#999999",
  gray600: "#777777", gray700: "#555555",
  textBody: "#444444", textDark: "#222222",
  accent: "#0066FF", accentSoft: "rgba(0,102,255,0.07)",
  footerBg: "#2c3034", footerText: "#adb5bd", footerDim: "#6c757d",
  ccelGold: "#E8A317",
  shadow: "0 1px 6px rgba(0,0,0,0.06)",
  shadowHover: "0 4px 16px rgba(0,0,0,0.10)",
};

const catColors = {
  dft: "#6C5CE7", catalysis: "#00A878", electrochemistry: "#0066FF",
  battery: "#E17055", ml: "#D63384", policy: "#B8860B",
};
const cc = id => catColors[id] || C.gray500;

const CATEGORIES = [
  { id: "dft", label: "DFT / Comp. Chem." },
  { id: "catalysis", label: "Catalysis" },
  { id: "electrochemistry", label: "Electrochem / FC" },
  { id: "battery", label: "Battery" },
  { id: "ml", label: "ML / MLIP" },
  { id: "policy", label: "Industry / Policy" },
];

const DEFAULT_GROUPS = [
  { id: "ccel", name: "CCEL" },
  { id: "norskov", name: "Norskov" },
  { id: "persson", name: "Persson" },
  { id: "curtarolo", name: "Curtarolo" },
  { id: "noguera", name: "Noguera" },
];

/* ===== Helper: get categories array from paper (backward compat) ===== */
function getPaperCats(d) {
  if (d.categories && Array.isArray(d.categories) && d.categories.length > 0) {
    return d.categories;
  }
  // Fallback: single category field
  const cat = d.category || d.cat || "";
  return cat ? [cat] : [];
}

/* ===== GLOBAL CSS ===== */
const CSS = `
@keyframes fadeUp{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}
.ccel-fade{animation:fadeUp .3s ease both}
.ccel-card{transition:box-shadow .2s,transform .15s}
.ccel-card:hover{box-shadow:${C.shadowHover};transform:translateY(-1px)}
.ccel-pill{transition:all .12s;cursor:pointer;user-select:none}
.ccel-pill:hover{opacity:.85}
.ccel-search:focus{border-color:${C.accent}!important;box-shadow:0 0 0 3px ${C.accentSoft}!important}
.ccel-tab{position:relative}
.ccel-tab::after{content:'';position:absolute;bottom:-1px;left:50%;width:0;height:2px;background:${C.accent};transition:all .2s;transform:translateX(-50%)}
.ccel-tab[data-active="true"]::after{width:100%}
*{box-sizing:border-box}
body{margin:0;padding:0}
`;

function useStyles(){
  useEffect(()=>{
    if(document.getElementById("ccel-css"))return;
    const s=document.createElement("style");s.id="ccel-css";s.textContent=CSS;document.head.appendChild(s);
  },[]);
}

/* ===== DATA LOADING ===== */
function useNewsData(){
  const [data,setData]=useState(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState(null);

  useEffect(()=>{
    const paths = ["./data/news.json", "/data/news.json", "../backend/data/news.json"];
    let found = false;

    async function tryLoad(){
      for(const p of paths){
        try{
          const r=await fetch(p);
          if(r.ok){
            const d=await r.json();
            setData(d);
            found=true;
            break;
          }
        }catch(e){}
      }
      if(!found) setError("news.json not found. Run the backend pipeline first.");
      setLoading(false);
    }
    tryLoad();
  },[]);

  return {data,loading,error};
}

/* ===== COMPONENTS ===== */
function CLine(){return <div style={{width:50,height:2,background:C.accent,margin:"8px auto 0"}}/>}

function Badge({label,color}){
  return <span style={{display:"inline-block",padding:"2px 9px",borderRadius:2,fontSize:11,fontWeight:600,lineHeight:"18px",color,background:color+"12"}}>{label}</span>;
}

function Pill({label,active,color,onClick}){
  return <button className="ccel-pill" onClick={onClick} style={{
    padding:"5px 14px",borderRadius:3,border:active?`1.5px solid ${color||C.accent}`:`1px solid ${C.border}`,
    background:active?(color||C.accent)+"12":"transparent",color:active?(color||C.accent):C.gray600,
    fontSize:12.5,fontWeight:active?700:400,fontFamily:"inherit",
  }}>{label}</button>;
}

function Stat({value,label,color}){
  return <div style={{textAlign:"center",padding:"10px 0"}}>
    <div style={{fontSize:26,fontWeight:800,color,lineHeight:1}}>{value}</div>
    <div style={{fontSize:11,color:C.gray500,marginTop:4}}>{label}</div>
  </div>;
}

function NewsCard({d,bm,onBm,groups}){
  const cats = getPaperCats(d);
  const grp=d.group?(groups||DEFAULT_GROUPS).find(g=>g.id===d.group):null;
  const isCcel=d.ccel||d.group==="ccel";
  const summary=d.summary||d.abstract||"";
  const rel=d.relevance||d.rel||0;
  const authors=d.authors_str||d.auth||(d.authors||[]).join("; ")||"";
  const date=d.date||"";

  return <article className="ccel-card ccel-fade" style={{
    background:C.white,borderLeft:isCcel?`4px solid ${C.accent}`:`1px solid ${C.borderLight}`,
    borderTop:`1px solid ${C.borderLight}`,borderRight:`1px solid ${C.borderLight}`,borderBottom:`1px solid ${C.borderLight}`,
    padding:"18px 20px",position:"relative",
  }}>
    {isCcel&&<span style={{position:"absolute",top:0,right:16,background:C.accent,color:C.white,fontSize:9.5,fontWeight:700,padding:"3px 8px 4px",borderRadius:"0 0 3px 3px",letterSpacing:.6,textTransform:"uppercase"}}>CCEL Group</span>}
    <div style={{display:"flex",alignItems:"center",gap:5,flexWrap:"wrap",marginBottom:8}}>
      {cats.map(catId => {
        const catDef = CATEGORIES.find(c=>c.id===catId);
        const color = cc(catId);
        const label = catDef ? catDef.label : catId;
        return <Badge key={catId} label={label} color={color}/>;
      })}
      {grp&&!isCcel&&<Badge label={grp.name} color={C.accent}/>}
      <span style={{fontSize:11,color:C.gray500}}>{d.source||""}</span>
      <span style={{fontSize:11,color:C.gray500}}>{date}</span>
      <div style={{marginLeft:"auto",display:"flex",alignItems:"center",gap:6}}>
        {rel>0&&<span style={{fontSize:10,fontWeight:600,color:rel>=90?C.accent:C.gray500,background:rel>=90?C.accentSoft:"transparent",padding:"1px 7px",borderRadius:2}}>Rel. {rel}</span>}
        <button onClick={()=>onBm(d.doi||d.title)} style={{background:"none",border:"none",cursor:"pointer",padding:0,fontSize:16,color:bm?C.ccelGold:C.gray300,transition:"color .15s"}}>{bm?"\u2605":"\u2606"}</button>
      </div>
    </div>
    <h3 style={{fontSize:15,fontWeight:700,color:C.textDark,margin:"0 0 3px",lineHeight:1.45,paddingRight:isCcel?80:0}}>{d.title||""}</h3>
    <p style={{fontSize:12,color:C.gray500,margin:"0 0 8px"}}>{authors}</p>
    <p style={{fontSize:13.5,color:C.textBody,margin:0,lineHeight:1.72}}>{summary}</p>
    {d.url&&<a href={d.url} target="_blank" rel="noopener noreferrer" style={{fontSize:12,color:C.accent,textDecoration:"none",display:"inline-block",marginTop:8}}>View paper &rarr;</a>}
  </article>;
}

function TrendChart({papers}){
  const byMonth={};
  const byCat={};
  (papers||[]).forEach(p=>{
    const d=p.date||"";
    const m=d.slice(0,7);
    const cats = getPaperCats(p);
    if(!m)return;
    cats.forEach(cat => {
      if(!byMonth[m])byMonth[m]={};
      byMonth[m][cat]=(byMonth[m][cat]||0)+1;
      byCat[cat]=(byCat[cat]||0)+1;
    });
  });

  const months=Object.keys(byMonth).sort().slice(-6);
  const topCats=Object.entries(byCat).sort((a,b)=>b[1]-a[1]).slice(0,5).map(e=>e[0]);

  if(months.length===0)return <div style={{padding:20,color:C.gray500,textAlign:"center"}}>Not enough data for trend chart.</div>;

  const W=600,H=200,PL=40,PR=14,PT=8,PB=30;
  const cW=W-PL-PR,cH=H-PT-PB;
  let mx=1;
  months.forEach(m=>{topCats.forEach(c=>{const v=(byMonth[m]||{})[c]||0;if(v>mx)mx=v;});});
  const sx=months.length>1?cW/(months.length-1):cW;

  return <div className="ccel-card" style={{background:C.white,border:`1px solid ${C.borderLight}`,padding:20,boxShadow:C.shadow}}>
    <h4 style={{fontSize:15,fontWeight:700,color:C.textDark,margin:"0 0 2px"}}>Topic Distribution</h4>
    <p style={{fontSize:11,color:C.gray500,margin:"0 0 12px"}}>Papers by category</p>
    <svg viewBox={`0 0 ${W} ${H}`} width="100%">
      {months.map((m,i)=><text key={m} x={PL+i*sx} y={H-6} textAnchor="middle" style={{fontSize:10,fill:C.gray500}}>{m}</text>)}
      {topCats.map(cat=>{
        const pts=months.map((m,i)=>[PL+i*sx,PT+cH*(1-((byMonth[m]||{})[cat]||0)/mx)]);
        const d=pts.map((p,i)=>`${i===0?"M":"L"}${p[0]} ${p[1]}`).join(" ");
        const last=pts[pts.length-1];
        return <g key={cat}>
          <path d={d} fill="none" stroke={cc(cat)} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
          <circle cx={last[0]} cy={last[1]} r="3.5" fill={cc(cat)}/>
        </g>;
      })}
    </svg>
    <div style={{display:"flex",flexWrap:"wrap",gap:"10px 16px",marginTop:8}}>
      {topCats.map(c=><div key={c} style={{display:"flex",alignItems:"center",gap:5}}>
        <span style={{width:14,height:3,borderRadius:1,background:cc(c),display:"inline-block"}}/>
        <span style={{fontSize:11,color:C.gray600}}>{CATEGORIES.find(x=>x.id===c)?.label||c}</span>
      </div>)}
    </div>
  </div>;
}

function SourceBreakdown({papers}){
  const sources={};
  (papers||[]).forEach(p=>{const s=p.source||"Unknown";sources[s]=(sources[s]||0)+1;});
  const sorted=Object.entries(sources).sort((a,b)=>b[1]-a[1]);
  const mx=sorted.length?sorted[0][1]:1;

  return <div className="ccel-card" style={{background:C.white,border:`1px solid ${C.borderLight}`,padding:20,boxShadow:C.shadow}}>
    <h4 style={{fontSize:15,fontWeight:700,color:C.textDark,margin:"0 0 2px"}}>Source Breakdown</h4>
    <p style={{fontSize:11,color:C.gray500,margin:"0 0 14px"}}>Papers by journal</p>
    <div style={{display:"flex",flexDirection:"column",gap:8}}>
      {sorted.map(([s,n])=><div key={s} style={{display:"flex",alignItems:"center",gap:12}}>
        <div style={{width:140,flexShrink:0,fontSize:12,fontWeight:500,color:C.textDark,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{s}</div>
        <div style={{flex:1,height:14,background:C.gray100,borderRadius:2,overflow:"hidden"}}>
          <div style={{width:`${(n/mx)*100}%`,height:"100%",background:C.accent,opacity:.6,borderRadius:2}}/>
        </div>
        <span style={{fontSize:12,fontWeight:700,color:C.textDark,width:28,textAlign:"right"}}>{n}</span>
      </div>)}
    </div>
  </div>;
}

function CategoryTrends({trends}){
  const [activeCat,setActiveCat]=useState(null);
  const [timeView,setTimeView]=useState("monthly"); // "monthly" or "yearly"

  if(!trends||Object.keys(trends).length===0) return null;

  const catOrder=["dft","catalysis","electrochemistry","battery","ml","policy"];
  const available=catOrder.filter(c=>trends[c]);

  // Default to first category
  const current=activeCat&&trends[activeCat]?activeCat:available[0];
  if(!current)return null;
  const t=trends[current];

  const text=timeView==="monthly"?t.monthly_trend:t.yearly_trend;
  const hotTopics=t.hot_topics||[];

  return <div className="ccel-card" style={{background:C.white,border:`1px solid ${C.borderLight}`,padding:0,boxShadow:C.shadow,overflow:"hidden"}}>
    {/* Header */}
    <div style={{padding:"16px 20px 0",borderBottom:`1px solid ${C.borderLight}`}}>
      <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:12}}>
        <div style={{width:30,height:30,borderRadius:3,background:C.textDark,display:"flex",alignItems:"center",justifyContent:"center",color:C.white,fontSize:10,fontWeight:800,flexShrink:0}}>AI</div>
        <div>
          <h4 style={{fontSize:15,fontWeight:700,margin:0,color:C.textDark}}>Category Research Trends</h4>
          <p style={{fontSize:11,color:C.gray500,margin:0}}>AI-generated analysis per research area</p>
        </div>
      </div>

      {/* Category tabs */}
      <div style={{display:"flex",gap:0,overflowX:"auto"}}>
        {available.map(catId=>{
          const label=CATEGORIES.find(c=>c.id===catId)?.label||catId;
          const color=cc(catId);
          const isActive=catId===current;
          const count=trends[catId]?.paper_count_monthly||0;
          return <button key={catId} onClick={()=>setActiveCat(catId)} style={{
            padding:"8px 14px",border:"none",borderBottom:isActive?`2.5px solid ${color}`:"2.5px solid transparent",
            background:"transparent",cursor:"pointer",fontFamily:"inherit",fontSize:11.5,
            fontWeight:isActive?700:400,color:isActive?color:C.gray500,transition:"all .15s",whiteSpace:"nowrap",
          }}>
            {label} <span style={{fontSize:10,opacity:.7}}>({count})</span>
          </button>;
        })}
      </div>
    </div>

    {/* Content */}
    <div style={{padding:"16px 20px"}}>
      {/* Time toggle */}
      <div style={{display:"flex",gap:3,marginBottom:14}}>
        {[["monthly","Recent 1 Month"],["yearly","Past 1 Year"]].map(([k,l])=>
          <button key={k} onClick={()=>setTimeView(k)} style={{
            padding:"4px 14px",border:"none",fontFamily:"inherit",cursor:"pointer",fontSize:11.5,fontWeight:600,borderRadius:2,
            background:timeView===k?cc(current)+"18":"transparent",
            color:timeView===k?cc(current):C.gray500,
          }}>{l}</button>
        )}
        <div style={{marginLeft:"auto",display:"flex",gap:5,alignItems:"center"}}>
          <span style={{fontSize:10,color:C.gray500}}>
            {timeView==="monthly"?t.paper_count_monthly:t.paper_count_yearly} papers
          </span>
        </div>
      </div>

      {/* Hot topics */}
      {hotTopics.length>0&&<div style={{display:"flex",gap:5,flexWrap:"wrap",marginBottom:12}}>
        {hotTopics.map((topic,i)=><span key={i} style={{
          padding:"2px 10px",borderRadius:10,fontSize:11,fontWeight:500,
          color:cc(current),background:cc(current)+"10",border:`1px solid ${cc(current)}25`,
        }}>{topic}</span>)}
      </div>}

      {/* Trend text */}
      {text?text.split("\n\n").map((p,i)=>
        <p key={i} style={{fontSize:13.5,color:C.textBody,lineHeight:1.75,margin:i===0?0:"10px 0 0"}}>{p}</p>
      ):<p style={{fontSize:13,color:C.gray500,textAlign:"center",padding:"20px 0"}}>
        {timeView==="yearly"?"Not enough historical data yet. Trends will appear after data accumulates.":"No trend data available. Run --digest to generate."}
      </p>}

      {/* Generated timestamp */}
      {t.generated_at&&<p style={{fontSize:10,color:C.gray300,marginTop:12,textAlign:"right"}}>
        Generated: {t.generated_at.slice(0,10)}
      </p>}
    </div>
  </div>;
}

function WeeklyDigest({text}){
  if(!text)return null;
  return <div className="ccel-card" style={{background:C.white,border:`1px solid ${C.borderLight}`,borderLeft:`4px solid ${C.accent}`,padding:20,boxShadow:C.shadow}}>
    <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:14}}>
      <div style={{width:30,height:30,borderRadius:3,background:C.accent,display:"flex",alignItems:"center",justifyContent:"center",color:C.white,fontSize:11,fontWeight:800,flexShrink:0}}>AI</div>
      <div>
        <h4 style={{fontSize:15,fontWeight:700,margin:0,color:C.textDark}}>Weekly Digest</h4>
        <p style={{fontSize:11,color:C.gray500,margin:0}}>Auto-generated by Gemini</p>
      </div>
    </div>
    {text.split("\n\n").map((p,i)=><p key={i} style={{fontSize:13.5,color:C.textBody,lineHeight:1.75,margin:i===0?0:"10px 0 0"}}>{p}</p>)}
  </div>;
}

/* ===== MAIN APP ===== */
export default function App(){
  useStyles();
  const {data,loading,error}=useNewsData();
  const [view,setView]=useState("feed");
  const [selectedCats,setSelectedCats]=useState(new Set()); // multi-select categories (AND logic)
  const [grps,setGrps]=useState(new Set());
  const [q,setQ]=useState("");
  const [bms,setBms]=useState(new Set());
  const [bmOnly,setBmOnly]=useState(false);
  const [sort,setSort]=useState("relevance");
  const [page,setPage]=useState(1);
  const searchRef=useRef(null);
  const PER_PAGE=20;

  useEffect(()=>{
    const h=e=>{if(e.key==="/"&&document.activeElement?.tagName!=="INPUT"){e.preventDefault();searchRef.current?.focus();}};
    window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h);
  },[]);

  // Reset page on filter change
  useEffect(()=>{setPage(1);},[selectedCats,grps,q,bmOnly,sort,view]);

  const toggleCat=id=>{
    setSelectedCats(prev=>{
      const n=new Set(prev);
      if(n.has(id)) n.delete(id); else n.add(id);
      return n;
    });
  };
  const toggleGrp=id=>setGrps(p=>{const n=new Set(p);n.has(id)?n.delete(id):n.add(id);return n;});
  const toggleBm=id=>setBms(p=>{const n=new Set(p);n.has(id)?n.delete(id):n.add(id);return n;});

  const papers=data?.papers||[];
  const allGroups=data?.groups||DEFAULT_GROUPS;
  const digest=data?.weekly_digest||"";
  const categoryTrends=data?.category_trends||{};
  const genDate=data?.date||data?.generated_at?.slice(0,10)||"";

  const filtered=useMemo(()=>{
    return papers.filter(d=>{
      const dCats = getPaperCats(d);

      // AND logic: paper must contain ALL selected categories
      if(selectedCats.size>0){
        for(const sc of selectedCats){
          if(!dCats.includes(sc)) return false;
        }
      }

      if(grps.size>0&&!grps.has(d.group))return false;
      if(bmOnly&&!bms.has(d.doi||d.title))return false;
      if(q){
        const s=q.toLowerCase();
        return (d.title||"").toLowerCase().includes(s)||(d.summary||d.abstract||"").toLowerCase().includes(s)||(d.authors_str||"").toLowerCase().includes(s);
      }
      return true;
    }).sort((a,b)=>{
      if(sort==="relevance")return (b.relevance||b.rel||0)-(a.relevance||a.rel||0);
      return ((b.date||"")<(a.date||"")?-1:1);
    });
  },[papers,selectedCats,grps,bmOnly,bms,q,sort]);

  const paged=filtered.slice(0,page*PER_PAGE);
  const hasMore=paged.length<filtered.length;

  const tabs=[{id:"feed",label:"Daily Feed"},{id:"landscape",label:"Research Landscape"},{id:"milestones",label:"Milestones"}];

  if(loading)return <div style={{fontFamily:"'Noto Sans KR',sans-serif",display:"flex",justifyContent:"center",alignItems:"center",height:"100vh",color:C.gray500}}>Loading...</div>;
  if(error)return <div style={{fontFamily:"'Noto Sans KR',sans-serif",display:"flex",justifyContent:"center",alignItems:"center",height:"100vh",color:C.gray500,flexDirection:"column",gap:8}}><div>{error}</div><div style={{fontSize:12}}>Place news.json in public/data/</div></div>;

  const ccelCnt=papers.filter(p=>p.ccel||p.group==="ccel").length;
  const highCnt=papers.filter(p=>(p.relevance||p.rel||0)>=90).length;

  // Count for active filter display
  const activeFilterCount = selectedCats.size;

  return <div style={{fontFamily:"'Noto Sans KR',-apple-system,BlinkMacSystemFont,sans-serif",background:C.white,minHeight:"100vh"}}>
    <link href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css" rel="stylesheet"/>

    {/* Navbar */}
    <nav style={{background:C.white,borderBottom:`1px solid ${C.border}`,position:"sticky",top:0,zIndex:100,boxShadow:"0 1px 3px rgba(0,0,0,0.04)"}}>
      <div style={{maxWidth:980,margin:"0 auto",padding:"0 20px",display:"flex",alignItems:"center",height:54}}>
        <div style={{display:"flex",alignItems:"baseline",gap:8,marginRight:32}}>
          <span style={{fontSize:20,fontWeight:800,color:C.textDark,letterSpacing:-.8}}>CCEL</span>
          <span style={{fontSize:12,color:C.gray500,fontWeight:400,letterSpacing:.5}}>DAILY NEWS</span>
        </div>
        <div style={{display:"flex",gap:2,height:"100%"}}>
          {tabs.map(t=><button key={t.id} className="ccel-tab" data-active={view===t.id} onClick={()=>setView(t.id)} style={{
            padding:"0 18px",border:"none",cursor:"pointer",fontFamily:"inherit",fontSize:13,fontWeight:view===t.id?700:400,height:"100%",background:"transparent",color:view===t.id?C.accent:C.gray600,transition:"color .15s",
          }}>{t.label}</button>)}
        </div>
        <div style={{marginLeft:"auto",fontSize:12,color:C.gray500}}>{genDate}</div>
      </div>
    </nav>

    {/* Hero */}
    <div style={{background:C.bg,padding:"22px 20px",borderBottom:`1px solid ${C.border}`}}>
      <div style={{maxWidth:980,margin:"0 auto",textAlign:"center"}}>
        <h1 style={{fontSize:18,fontWeight:700,color:C.textDark,margin:"0 0 4px",letterSpacing:-.3}}>Computational Catalysis and Emerging Materials Laboratory</h1>
        <p style={{fontSize:12.5,color:C.gray600,margin:0}}>Seoul National University | Prof. Jeong Woo Han</p>
      </div>
    </div>

    {/* Main */}
    <div style={{maxWidth:980,margin:"0 auto",padding:"20px 20px 0"}}>

      {/* Filters */}
      <div style={{background:C.bgAlt,border:`1px solid ${C.borderLight}`,padding:"14px 16px",marginBottom:22}}>
        <div style={{marginBottom:10}}>
          <span style={{fontSize:10.5,color:C.gray500,fontWeight:600,textTransform:"uppercase",letterSpacing:1}}>Groups</span>
          <div style={{display:"flex",gap:5,flexWrap:"wrap",marginTop:5}}>
            {allGroups.map(g=><Pill key={g.id} label={g.name} active={grps.has(g.id)} color={C.accent} onClick={()=>toggleGrp(g.id)}/>)}
          </div>
        </div>
        <div>
          <div style={{display:"flex",alignItems:"center",gap:8}}>
            <span style={{fontSize:10.5,color:C.gray500,fontWeight:600,textTransform:"uppercase",letterSpacing:1}}>Categories</span>
            {activeFilterCount>=2&&<span style={{fontSize:10,color:C.accent,fontWeight:600}}>AND filter ({activeFilterCount} selected)</span>}
            {activeFilterCount>0&&<button onClick={()=>setSelectedCats(new Set())} style={{fontSize:10,color:C.gray500,background:"none",border:"none",cursor:"pointer",fontFamily:"inherit",textDecoration:"underline",padding:0}}>Clear</button>}
          </div>
          <div style={{display:"flex",gap:5,flexWrap:"wrap",marginTop:5}}>
            {CATEGORIES.map(c=><Pill key={c.id} label={c.label} active={selectedCats.has(c.id)} color={cc(c.id)} onClick={()=>toggleCat(c.id)}/>)}
          </div>
        </div>
      </div>

      {/* DAILY FEED */}
      {view==="feed"&&<div>
        <div style={{textAlign:"center",marginBottom:20}}>
          <h2 style={{fontSize:20,fontWeight:700,color:C.textDark,margin:0}}>Daily Feed</h2>
          <CLine/>
        </div>

        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",background:C.white,border:`1px solid ${C.borderLight}`,marginBottom:16,boxShadow:C.shadow}}>
          <Stat value={papers.length} label="Total papers" color={C.accent}/>
          <Stat value={ccelCnt} label="CCEL group" color={C.ccelGold}/>
          <Stat value={highCnt} label="High relevance" color="#E17055"/>
        </div>

        <input ref={searchRef} className="ccel-search" type="text" placeholder='Search papers, authors, keywords...  ("/" to focus)' value={q} onChange={e=>setQ(e.target.value)} style={{
          width:"100%",padding:"10px 14px",border:`1px solid ${C.border}`,background:C.white,color:C.textDark,fontSize:13,fontFamily:"inherit",outline:"none",marginBottom:12,
        }}/>

        <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}>
          <div style={{display:"flex",alignItems:"center",gap:8}}>
            <div style={{display:"flex",gap:3}}>
              {[["relevance","Relevance"],["date","Latest"]].map(([k,l])=><button key={k} onClick={()=>setSort(k)} style={{
                padding:"4px 12px",border:"none",fontFamily:"inherit",cursor:"pointer",fontSize:11.5,fontWeight:600,
                background:sort===k?C.textDark:"transparent",color:sort===k?C.white:C.gray500,
              }}>{l}</button>)}
            </div>
            <span style={{fontSize:11,color:C.gray500}}>{filtered.length} papers{selectedCats.size>0?` (filtered)`:""}</span>
          </div>
          <button className="ccel-pill" onClick={()=>setBmOnly(!bmOnly)} style={{
            padding:"4px 12px",fontFamily:"inherit",border:bmOnly?`1.5px solid ${C.ccelGold}`:`1px solid ${C.border}`,
            background:bmOnly?C.ccelGold+"10":"transparent",color:bmOnly?C.ccelGold:C.gray500,
            fontSize:11.5,fontWeight:600,borderRadius:3,
          }}>{bmOnly?`\u2605 (${bms.size})`:"\u2606 Bookmarks"}</button>
        </div>

        <div style={{display:"flex",flexDirection:"column",gap:8}}>
          {paged.length===0?<div style={{textAlign:"center",padding:50,color:C.gray500,fontSize:13}}>No results.{selectedCats.size>=2?" Try removing a category filter.":""}</div>
            :paged.map((d,i)=><div key={d.doi||d.title||i} style={{animationDelay:`${Math.min(i,10)*0.03}s`}}><NewsCard d={d} bm={bms.has(d.doi||d.title)} onBm={toggleBm} groups={allGroups}/></div>)
          }
        </div>
        {hasMore&&<div style={{textAlign:"center",padding:"20px 0"}}>
          <button onClick={()=>setPage(p=>p+1)} style={{padding:"10px 32px",border:`1px solid ${C.border}`,background:C.white,color:C.textDark,fontSize:13,fontWeight:600,cursor:"pointer",fontFamily:"inherit",borderRadius:3}}>Load more ({filtered.length-paged.length} remaining)</button>
        </div>}
      </div>}

      {/* RESEARCH LANDSCAPE */}
      {view==="landscape"&&<div>
        <div style={{textAlign:"center",marginBottom:20}}>
          <h2 style={{fontSize:20,fontWeight:700,color:C.textDark,margin:0}}>Research Landscape</h2>
          <p style={{fontSize:13,color:C.gray500,margin:"4px 0 0"}}>Trends, source breakdown, and AI-powered analysis</p>
          <CLine/>
        </div>
        <div style={{display:"flex",flexDirection:"column",gap:14}}>
          <WeeklyDigest text={digest}/>
          <CategoryTrends trends={categoryTrends}/>
          <TrendChart papers={papers}/>
          <SourceBreakdown papers={papers}/>
        </div>
      </div>}

      {/* MILESTONES */}
      {view==="milestones"&&<div>
        <div style={{textAlign:"center",marginBottom:20}}>
          <h2 style={{fontSize:20,fontWeight:700,color:C.textDark,margin:0}}>Milestones</h2>
          <p style={{fontSize:13,color:C.gray500,margin:"4px 0 0"}}>Coming soon: curated landmark papers</p>
          <CLine/>
        </div>
        <div style={{textAlign:"center",padding:"60px 20px",color:C.gray500}}>
          <p style={{fontSize:14}}>Milestone papers will be curated by lab members.</p>
          <p style={{fontSize:12,marginTop:8}}>Once added, they will appear here as a timeline of key papers in each research area.</p>
        </div>
      </div>}
    </div>

    {/* Footer */}
    <footer style={{background:C.footerBg,padding:"28px 20px",marginTop:50,textAlign:"center"}}>
      <h3 style={{fontSize:14,fontWeight:600,color:C.white,margin:"0 0 6px"}}>Computational Catalysis and Emerging Materials Laboratory</h3>
      <p style={{fontSize:11,color:C.footerText,margin:"0 0 3px",lineHeight:1.6}}>Department of Materials Science and Engineering, Seoul National University<br/>1 Gwanak-ro, Gwanak-gu, Seoul 08826, Korea</p>
      <div style={{width:40,height:1,background:C.footerDim,margin:"12px auto"}}/>
      <p style={{fontSize:10.5,color:C.footerDim,margin:0}}>CCEL Daily News | Powered by Gemini API + arXiv + RSS | Auto-updated via GitHub Actions</p>
    </footer>
  </div>;
}
