/**
 * ISO 4 / ACS-style official abbreviations for journal names.
 * Keys match normalizeSource() output from App.jsx (canonical venue strings).
 */
export const JOURNAL_DISPLAY_ISO4 = {
  arXiv: "arXiv",
  Unknown: "—",

  JACS: "JACS",
  "JACS Au": "JACS Au",

  "ACS Applied Electronic Materials": "ACS Appl. Electron. Mater.",
  "ACS Applied Energy Materials": "ACS Appl. Energy Mater.",
  "ACS Applied Materials & Interfaces": "ACS Appl. Mater. Interfaces",
  "ACS Applied Optical Materials": "ACS Appl. Opt. Mater.",
  "ACS Applied Polymer Materials": "ACS Appl. Polym. Mater.",
  "ACS Catalysis": "ACS Catal.",
  "ACS Energy Letters": "ACS Energy Lett.",
  "ACS Macro Letters": "ACS Macro Lett.",
  "ACS Materials Letters": "ACS Mater. Lett.",
  "ACS Nano": "ACS Nano",
  "ACS Pharmacology & Translational Science": "ACS Pharmacol. Transl. Sci.",
  "ACS Sustainable Chemistry & Engineering": "ACS Sustainable Chem. Eng.",

  Science: "Science",
  Nature: "Nature",
  "Science Advances": "Sci. Adv.",

  "Nature Materials": "Nat. Mater.",
  "Nature Energy": "Nat. Energy",
  "Nature Catalysis": "Nat. Catal.",
  "Nature Communications": "Nat. Commun.",
  "Nature Computational Science": "Nat. Comput. Sci.",
  "Nature Chemistry": "Nat. Chem.",
  "Nature Nanotechnology": "Nat. Nanotechnol.",
  "Nature Physics": "Nat. Phys.",
  "Nature Biotechnology": "Nat. Biotechnol.",
  "Nature Machine Intelligence": "Nat. Mach. Intell.",
  "Nature Sustainability": "Nat. Sustainability",
  "Nature Synthesis": "Nat. Synth.",
  "Nature Reviews Chemistry": "Nat. Rev. Chem.",
  "Nature Reviews Materials": "Nat. Rev. Mater.",
  "Nature Reviews Physics": "Nat. Rev. Phys.",
  "Nature Reviews Methods Primers": "Nat. Rev. Methods Primers",

  "Advanced Energy Materials": "Adv. Energy Mater.",
  "Advanced Functional Materials": "Adv. Funct. Mater.",
  "Advanced Materials": "Adv. Mater.",
  "Advanced Optical Materials": "Adv. Opt. Mater.",
  "Advanced Healthcare Materials": "Adv. Healthcare Mater.",
  "Advanced Science": "Adv. Sci.",
  "Advanced Composites and Hybrid Materials": "Adv. Compos. Hybrid Mater.",

  "Angewandte Chemie": "Angew. Chem.",
  "Angewandte Chemie International Edition": "Angew. Chem. Int. Ed.",

  "Chemical Science": "Chem. Sci.",
  "Chemistry of Materials": "Chem. Mater.",
  "Chemical Communications": "Chem. Commun.",
  "Chemical Reviews": "Chem. Rev.",
  "Chemical Society Reviews": "Chem. Soc. Rev.",
  "Chemistry - A European Journal": "Chem. Eur. J.",

  "Digital Discovery": "Digital Discovery",

  "Journal of Chemical Theory and Computation": "J. Chem. Theory Comput.",
  "Journal of Materials Chemistry A": "J. Mater. Chem. A",
  "Journal of Materials Chemistry C": "J. Mater. Chem. C",

  "Machine Learning Science and Technology": "Mach. Learn.: Sci. Technol.",

  "npj Computational Materials": "npj Comput. Mater.",

  "Energy & Environmental Science": "Energy Environ. Sci.",
  "Energy Environ. Sci.": "Energy Environ. Sci.",

  "Scientific Data": "Sci. Data",
  "The Journal of Chemical Physics": "J. Chem. Phys.",
  "The Journal of Physical Chemistry A": "J. Phys. Chem. A",
  "The Journal of Physical Chemistry B": "J. Phys. Chem. B",
  "The Journal of Physical Chemistry C": "J. Phys. Chem. C",
  "The Journal of Physical Chemistry Letters": "J. Phys. Chem. Lett.",

  // Additional venues present in news.json (ISO 4–style / common CA abbreviations)
  "AI for Science": "AI Sci.",
  "Accounts of Chemical Research": "Acc. Chem. Res.",
  "Acta Materialia": "Acta Mater.",
  "Annual Review of Chemical and Biomolecular Engineering": "Annu. Rev. Chem. Biomol. Eng.",
  "Annual Review of Physical Chemistry": "Annu. Rev. Phys. Chem.",
  "Applied and Computational Engineering": "Appl. Comput. Eng.",
  "Astronomy and Astrophysics": "Astron. Astrophys.",
  "Autonomous Robots": "Auton. Robots",
  "Batteries & Supercaps": "Batteries Supercaps",
  "Carbon Energy": "Carbon Energy",
  "Catalysis Letters": "Catal. Lett.",
  Catalysts: "Catalysts",
  "Cellular and Molecular Life Sciences": "Cell. Mol. Life Sci.",
  ChemPhysChem: "ChemPhysChem",
  ChemPlusChem: "ChemPlusChem",
  ChemSusChem: "ChemSusChem",
  "Chinese Physics B": "Chin. Phys. B",
  "Communications Chemistry": "Commun. Chem.",
  "Communications Physics": "Commun. Phys.",
  "Communications in computer and information science": "Commun. Comput. Inf. Sci.",
  "Computational Materials Science": "Comput. Mater. Sci.",
  "Current Opinion in Chemical Engineering": "Curr. Opin. Chem. Eng.",
  "Drug Delivery and Translational Research": "Drug Delivery Transl. Res.",
  "EES Catalysis": "EES Catal.",
  "Electronic Structure": "Electron. Struct.",
  "Energy & Fuels": "Energy Fuels",
  "Energy Advances": "Energy Adv.",
  "Experimental Mechanics": "Exp. Mech.",
  "Faraday Discussions": "Faraday Discuss.",
  "Frontiers in Chemistry": "Front. Chem.",
  "Frontiers in Materials": "Front. Mater.",
  "Frontiers in Physics": "Front. Phys.",
  "Frontiers in Plant Science": "Front. Plant Sci.",
  "High Entropy Alloys & Materials": "High Entropy Alloys Mater.",
  IUCrJ: "IUCrJ",
  "Inorganic Chemistry": "Inorg. Chem.",
  Joule: "Joule",
  "Journal of Advanced Ceramics": "J. Adv. Ceram.",
  "Journal of Chemical & Engineering Data": "J. Chem. Eng. Data",
  "Journal of Chemical Information and Modeling": "J. Chem. Inf. Model.",
  "Journal of Cheminformatics": "J. Cheminformatics",
  "Journal of Computational Chemistry": "J. Comput. Chem.",
  "Journal of Fluorescence": "J. Fluoresc.",
  "Journal of Geophysical Research Solid Earth": "J. Geophys. Res. Solid Earth",
  "Journal of Mechanical Science and Technology": "J. Mech. Sci. Technol.",
  "Journal of Personalized Medicine": "J. Pers. Med.",
  "Journal of Phase Equilibria and Diffusion": "J. Phase Equilibria Diffus.",
  "Journal of Physics D Applied Physics": "J. Phys. D",
  "Journal of Physics Materials": "J. Phys. Mater.",
  "Journal of Physics Photonics": "J. Phys. Photonics",
  "Journal of The Electrochemical Society": "J. Electrochem. Soc.",
  "Journal of materials research/Pratt's guide to venture capital sources": "J. Mater. Res.",
  "Journal of the Korean Physical Society": "J. Korean Phys. Soc.",
  "Korean Journal of Chemical Engineering": "Korean J. Chem. Eng.",
  Langmuir: "Langmuir",
  "Lecture notes in computer science": "Lect. Notes Comput. Sci.",
  "Lecture notes in control and information sciences": "Lect. Notes Control Inf. Sci.",
  "MRS Bulletin": "MRS Bull.",
  Machines: "Machines",
  Magnetochemistry: "Magnetochemistry",
  "Materials Advances": "Mater. Adv.",
  "Materials Genome Engineering Advances": "Mater. Genome Eng. Adv.",
  "Materials Horizons": "Mater. Horiz.",
  "Materials and Interfaces": "Mater. Interfaces",
  Matter: "Matter",
  "Methods in molecular biology": "Methods Mol. Biol.",
  "Molecular Diagnosis & Therapy": "Mol. Diagn. Ther.",
  "Molecular Systems Design & Engineering": "Mol. Syst. Des. Eng.",
  "Nano Energy": "Nano Energy",
  "Nano Letters": "Nano Lett.",
  "Nano-Micro Letters": "Nano-Micro Lett.",
  Nanoscale: "Nanoscale",
  "Nanoscale Advances": "Nanoscale Adv.",
  "PLoS ONE": "PLoS ONE",
  "PRX Energy": "PRX Energy",
  "PRX Quantum": "PRX Quantum",
  "Physical Chemistry Chemical Physics": "Phys. Chem. Chem. Phys.",
  "Physical Review Applied": "Phys. Rev. Appl.",
  "Physical Review Letters": "Phys. Rev. Lett.",
  "Physical Review Materials": "Phys. Rev. Mater.",
  "Physical review. A/Physical review, A": "Phys. Rev. A",
  "Physical review. B./Physical review. B": "Phys. Rev. B",
  "Physical review. E": "Phys. Rev. E",
  "Polymer Chemistry": "Polym. Chem.",
  PubMed: "PubMed",
  Quantum: "Quantum",
  "Quantum Science and Technology": "Quantum Sci. Technol.",
  "RSC Advances": "RSC Adv.",
  "RSC Sustainability": "RSC Sustainability",
  "Research Square (Research Square)": "Research Square",
  "Science and Technology of Engineering Chemistry and Environmental Protection": "Sci. Technol. Eng. Chem. Environ. Prot.",
  "Scientific Reports": "Sci. Rep.",
  Small: "Small",
  "Small Methods": "Small Methods",
  "Small Structures": "Small Struct.",
  "The Astrophysical Journal": "Astrophys. J.",
  "The Journal of Open Source Software": "J. Open Source Softw.",
  "The Journal of Supercritical Fluids": "J. Supercrit. Fluids",
  "Topics in Catalysis": "Top. Catal.",
  "OSTI OAI (U.S. Department of Energy Office of Scientific and Technical Information)": "OSTI OAI",
  Organometallics: "Organometallics",
  "eScholarship (California Digital Library)": "eScholarship",
};

/**
 * @param {string} full normalized journal name (same as filter key)
 * @returns {string} official-style abbreviation for UI
 */
export function getJournalDisplayLabel(full) {
  if (full == null || full === "") return "";
  if (Object.prototype.hasOwnProperty.call(JOURNAL_DISPLAY_ISO4, full)) {
    return JOURNAL_DISPLAY_ISO4[full];
  }
  if (full.length <= 32) return full;
  return full.slice(0, 30) + "\u2026";
}
